-- CreateTable
CREATE TABLE "KHACH_HANG" (
    "MA_KH" VARCHAR(50) NOT NULL,
    "TEN" VARCHAR(100),
    "SDT" VARCHAR(15),
    "EMAIL" VARCHAR(100),
    "MAT_KHAU" VARCHAR(255),
    "GOOGLE_ID" VARCHAR(100),
    "FACEBOOK_ID" VARCHAR(100),
    "FCM_TOKEN" TEXT,

    CONSTRAINT "KHACH_HANG_pkey" PRIMARY KEY ("MA_KH")
);

-- CreateTable
CREATE TABLE "SAN_PHAM" (
    "MA_SP" VARCHAR(50) NOT NULL,
    "TEN_SP" VARCHAR(100),
    "GIA_BAN" DECIMAL(12,2),
    "DANH_MUC" VARCHAR(50),
    "HINH_ANH" TEXT,
    "TRANG_THAI_MON" BOOLEAN DEFAULT true,

    CONSTRAINT "SAN_PHAM_pkey" PRIMARY KEY ("MA_SP")
);

-- CreateTable
CREATE TABLE "TOPPING" (
    "MA_TOPPING" VARCHAR(50) NOT NULL,
    "TEN_TOPPING" VARCHAR(100),
    "GIA_TOPPING" DECIMAL(12,2),

    CONSTRAINT "TOPPING_pkey" PRIMARY KEY ("MA_TOPPING")
);

-- CreateTable
CREATE TABLE "DON_HANG" (
    "MA_DH" VARCHAR(50) NOT NULL,
    "MA_KH" VARCHAR(50),
    "NGAY_DAT" TIMESTAMP(3) DEFAULT CURRENT_TIMESTAMP,
    "TONG_TIEN" DECIMAL(12,2),
    "PHI_SHIP" DECIMAL(12,2),
    "TRANG_THAI" VARCHAR(30),
    "PTTT" VARCHAR(20),
    "MA_GIAO_DICH_CONG" VARCHAR(100),
    "MA_VAN_DON" VARCHAR(100),
    "DIA_CHI_GIAO_HANG" TEXT,
    "LATITUDE" DECIMAL(10,8),
    "LONGITUDE" DECIMAL(11,8),

    CONSTRAINT "DON_HANG_pkey" PRIMARY KEY ("MA_DH")
);

-- CreateTable
CREATE TABLE "CHI_TIET_DON_HANG" (
    "MA_CHI_TIET" VARCHAR(50) NOT NULL,
    "MA_DH" VARCHAR(50),
    "MA_SP" VARCHAR(50),
    "SOLUONG" INTEGER,
    "THANHTIEN" DECIMAL(12,2),

    CONSTRAINT "CHI_TIET_DON_HANG_pkey" PRIMARY KEY ("MA_CHI_TIET")
);

-- CreateTable
CREATE TABLE "THEM_TOPPING" (
    "MA_CHI_TIET" VARCHAR(50) NOT NULL,
    "MA_TOPPING" VARCHAR(50) NOT NULL,

    CONSTRAINT "THEM_TOPPING_pkey" PRIMARY KEY ("MA_CHI_TIET","MA_TOPPING")
);

-- AddForeignKey
ALTER TABLE "DON_HANG" ADD CONSTRAINT "DON_HANG_MA_KH_fkey" FOREIGN KEY ("MA_KH") REFERENCES "KHACH_HANG"("MA_KH") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CHI_TIET_DON_HANG" ADD CONSTRAINT "CHI_TIET_DON_HANG_MA_DH_fkey" FOREIGN KEY ("MA_DH") REFERENCES "DON_HANG"("MA_DH") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "CHI_TIET_DON_HANG" ADD CONSTRAINT "CHI_TIET_DON_HANG_MA_SP_fkey" FOREIGN KEY ("MA_SP") REFERENCES "SAN_PHAM"("MA_SP") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "THEM_TOPPING" ADD CONSTRAINT "THEM_TOPPING_MA_CHI_TIET_fkey" FOREIGN KEY ("MA_CHI_TIET") REFERENCES "CHI_TIET_DON_HANG"("MA_CHI_TIET") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "THEM_TOPPING" ADD CONSTRAINT "THEM_TOPPING_MA_TOPPING_fkey" FOREIGN KEY ("MA_TOPPING") REFERENCES "TOPPING"("MA_TOPPING") ON DELETE RESTRICT ON UPDATE CASCADE;
